name             'mongodb'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures mongodb'
long_description 'Installs/Configures mongodb'
version          '0.1.0'
